-- 1. Create a table for public profiles (links to auth.users)
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  updated_at timestamp with time zone,
  constraint username_length check (char_length(username) >= 3)
);

-- 2. Enable RLS (Security)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update their own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 3. Create a table for scores
create table scores (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  username text not null, -- denormalized for easier querying
  level int not null,
  mode text not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS for scores
alter table scores enable row level security;

create policy "Scores are viewable by everyone."
  on scores for select
  using ( true );

create policy "Authenticated users can insert scores."
  on scores for insert
  with check ( auth.role() = 'authenticated' );
